---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->


## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat beneath a sunny sky,

Lingering onward dreamily

In an evening of July —

Children three that nestle near,

Eager eye and willing ear,


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
 
Guilty Guilty Guilty for actions that took my sympathy  
Shackles around my wrist shackles at my feet  
Prom and high school graduation these eyes will never see  
My heart said, Oh well  
At least you will no longer have to endure your daily home   abuse  
I grew into a woman unbalanced behind those wire fences  
Recall (3xs) that’s all I knew  
Always committing some illegal offenses straight to the   SHU  
These eyes have seen the bottom of boots,  
Mace in the face,  
The heavy blue dress while people watch you 24hrs a day,  
A lock in a sock,  
Shall I go on?  
My heart was always heavy  
  